# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"\xe4\x01\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12-\n\x0bpublic_data\x18\x06 \x01(\x0b\x32\x18.event.AccessLevelPublic\x12\'\n\x08vip_data\x18\x07 \x01(\x0b\x32\x15.event.AccessLevelVIP\x12+\n\nstaff_data\x18\x08 \x01(\x0b\x32\x17.event.AccessLevelStaff\"[\n\x11\x41\x63\x63\x65ssLevelPublic\x12\x16\n\x0e\x61genda_summary\x18\x01 \x01(\t\x12\x12\n\ndress_code\x18\x02 \x01(\t\x12\x1a\n\x12general_guidelines\x18\x03 \x03(\t\"^\n\x0e\x41\x63\x63\x65ssLevelVIP\x12\x1b\n\x13vip_lounge_location\x18\x01 \x01(\t\x12\x13\n\x0bvip_contact\x18\x02 \x01(\t\x12\x1a\n\x12\x65xclusive_sessions\x18\x03 \x03(\t\"h\n\x10\x41\x63\x63\x65ssLevelStaff\x12\x19\n\x11internal_briefing\x18\x01 \x01(\t\x12\x16\n\x0esecurity_codes\x18\x02 \x03(\t\x12!\n\x19requires_background_check\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=23
  _globals['_EVENT']._serialized_end=251
  _globals['_ACCESSLEVELPUBLIC']._serialized_start=253
  _globals['_ACCESSLEVELPUBLIC']._serialized_end=344
  _globals['_ACCESSLEVELVIP']._serialized_start=346
  _globals['_ACCESSLEVELVIP']._serialized_end=440
  _globals['_ACCESSLEVELSTAFF']._serialized_start=442
  _globals['_ACCESSLEVELSTAFF']._serialized_end=546
# @@protoc_insertion_point(module_scope)
